version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: egg_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - shared_data:/shared
      - ./backend:/app
      - ./backend/wait-for-it.sh:/app/wait-for-it.sh:ro
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: egg_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - shared_data:/shared
      - ./frontend:/app
      - ./frontend/wait-for-it.sh:/app/wait-for-it.sh:ro
    restart: always
volumes:
  shared_data: